### ISSUE TITLE
webcrawl.py and datajobs.py removed?

### ISSUE THREAD

**Issue by MoHabib88** [yoyolin/DataScienceJobs#1]
Was wondering what the difference between the two python scripts was.

**Comment by yoyolin** [comment]
datajobs.py mainly acquire everything (job, company, location, date, url) returned by indeed API given job queries (data+scientist, data+analyst, data+engineer, machine+learner) and save as csv formatted file.

webcrawl.py performs web crawling and language processing for every job saved using its url. Sorry that I didn't document properly for them. 

btw, how could you see files removed? I thought they were hidden - yes I am pretty new to github.

**Comment by MoHabib88** [comment]
You mention them in Readme.md so I assumed you removed them.

Trying to run your code on ipythonnotebook to find the skillsets in demand for "mechanical engineer." Looks like creating a crawler _with_ language processor is my next step.

Thanks for the quick response.

**Comment by yoyolin** [comment]
Hey I just uploaded them. 

The project and files posted here were intended for a submission for final project for one of my courses. I submitted those two *.py files directly so I forgot to post them here.

Now you can try with your mechanical engineer results :)

**Comment by MoHabib88** [comment]
Thank you!
